cred3:
  bulk_center:
  - 10
  - 10
  bulk_size: 10
  dark_shm_path: /dev/shm/cred3_dark.im.shm
  img_shm_path: /dev/shm/cred1.im.shm
  output_centers:
  - - 0
    - 0
  - - 0
    - 0
  - - 0
    - 0
  - - 0
    - 0
  output_sizes: 10
  semid: 0
  use_dark: true
dm:
  config_path: ./config/DM/DM_config.json
  injection_segments:
  - 138
  - 137
  - 136
  - 135
  serial_number: 27BW007#051
  stabilization_time: 0.001
filter_wheel:
  port: /dev/ttyUSBthorlabs
photonic_chip:
  arch: 6
  bright_output: 0
  driver_port_match: 2341:8036
pupil_mask:
  newport_home: 56.15
  newport_port: /dev/ttyUSBnewport
  selected_mask: 4
  zaber_h_pos: 150000
  zaber_port: /dev/ttyUSBzaber
  zaber_v_pos: 150000
